name: E2E Tests (Optional)

on:
  # Manual trigger only - not part of CI
  workflow_dispatch:
    inputs:
      browser:
        description: 'Browser to test (chromium, firefox, webkit, mobile, all)'
        required: false
        default: 'chromium'
        type: choice
        options:
          - chromium
          - firefox  
          - webkit
          - mobile
          - all

jobs:
  e2e:
    name: E2E Tests
    runs-on: ubuntu-latest
    timeout-minutes: 30

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Install Playwright browsers
        run: |
          if [ "${{ github.event.inputs.browser }}" = "all" ]; then
            npx playwright install --with-deps
          else
            npx playwright install --with-deps ${{ github.event.inputs.browser }}
          fi

      - name: Build application
        run: npm run build
        env:
          NODE_ENV: test

      - name: Run E2E tests
        run: |
          if [ "${{ github.event.inputs.browser }}" = "all" ]; then
            npm run test:e2e
          else
            npx playwright test --project=${{ github.event.inputs.browser }}
          fi
        continue-on-error: false

      - name: Upload Playwright report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: playwright-report-${{ github.event.inputs.browser }}
          path: playwright-report/
          retention-days: 7

      - name: Upload test results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: e2e-results-${{ github.event.inputs.browser }}
          path: test-results/
          retention-days: 7